BAG OF WORDS
BoW  -> kelimeler nasıl vektör haline gelir

In [13]:
!pip install scikit-learn

In [14]:
from sklearn.feature_extraction.text import CountVectorizer

In [15]:
import pandas as pd
df=pd.read_csv("data/nlp.csv",index_col=0)
df.head()

Text
0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...
1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...
2  Öncelikle yapay zekanın ne olduğunu, #dijitala...
3  9. Baidu Research: Çin'in önde gelen arama mot...
4  4. Microsoft AI: Microsoft'un yapay zeka tekno...

In [16]:
import on_islem

In [17]:
df["Text_2"]=df["Text"].apply(on_islem.pre_processing)
df["Text_2"]=df["Text_2"].apply(on_islem.remove_space)
df.head()

Text   
0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...  \
1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2  Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3  9. Baidu Research: Çin'in önde gelen arama mot...   
4  4. Microsoft AI: Microsoft'un yapay zeka tekno...   

                                              Text_2  
0  [yapay, zeka, nedir, ne, işe, yarar, yapay, ze...  
1  [veri, analiz, edin, chatgptyi, kullanarak, do...  
2  [öncelik, yapay, zeka, ne, olduğunu, iç, ne, ö...  
3  [baidu, research, çin, ön, gele, ara, motor, b...  
4  [microsoft, ai, microsoft, yapay, zeka, teknol...

In [18]:
# boş liste kontrolü

df[df["Text_2"].str[0].isnull()]

Text Text_2
194  #hesaplamalısosyalbilimler #computationalsocia...     []
464  #investment #software #technology #tech #innov...     []

In [19]:
df_index=df[df["Text_2"].str[0].isnull()].index
df=df.drop(df_index)
df=df.reset_index()
del df["index"]

df[df["Text_2"].str[0].isnull()]

Empty DataFrame
Columns: [Text, Text_2]
Index: []

In [20]:
df.head()

Text   
0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...  \
1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2  Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3  9. Baidu Research: Çin'in önde gelen arama mot...   
4  4. Microsoft AI: Microsoft'un yapay zeka tekno...   

                                              Text_2  
0  [yapay, zeka, nedir, ne, işe, yarar, yapay, ze...  
1  [veri, analiz, edin, chatgptyi, kullanarak, do...  
2  [öncelik, yapay, zeka, ne, olduğunu, iç, ne, ö...  
3  [baidu, research, çin, ön, gele, ara, motor, b...  
4  [microsoft, ai, microsoft, yapay, zeka, teknol...

In [21]:
df["Text_2"]

0      [yapay, zeka, nedir, ne, işe, yarar, yapay, ze...
1      [veri, analiz, edin, chatgptyi, kullanarak, do...
2      [öncelik, yapay, zeka, ne, olduğunu, iç, ne, ö...
3      [baidu, research, çin, ön, gele, ara, motor, b...
4      [microsoft, ai, microsoft, yapay, zeka, teknol...
                             ...                        
851    [doğal, dil, işle, alan, yük, lisansdoktor, ya...
852                              [dogal, dil, isle, şey]
853    [bir, ver, madencilik, ve, doğal, dil, işle, u...
854    [doğal, dil, işleme, il, ilgil, deney, ola, ya...
855    [hafta, öğrencilik, hayat, kaldık, yer, deva, ...
Name: Text_2, Length: 856, dtype: object

In [22]:
df["Text_3"]=[' '.join(w for w in item) for item in df["Text_2"]]
df

Text   
0    Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...  \
1    🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2    Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3    9. Baidu Research: Çin'in önde gelen arama mot...   
4    4. Microsoft AI: Microsoft'un yapay zeka tekno...   
..                                                 ...   
851  doğal dil işleme alanında yüksek lisans-doktor...   
852                           dogal dil isleme şeyleri   
853  Bir veri madenciliği ve doğal dil işleme uygul...   
854  "Doğal dil işleme" ile ilgili deneyimi olan ya...   
855  Haftaya öğrencilik hayatıma kaldığım yerden de...   

                                                Text_2   
0    [yapay, zeka, nedir, ne, işe, yarar, yapay, ze...  \
1    [veri, analiz, edin, chatgptyi, kullanarak, do...   
2    [öncelik, yapay, zeka, ne, olduğunu, iç, ne, ö...   
3    [baidu, research, çin, ön, gele, ara, motor, b...   
4    [microsoft, ai, microsoft, yapay, zeka, teknol...   
..                                                 ...   
851  [doğal, dil, işle, alan, yük, lisansdoktor, ya...   
852                            [dogal, dil, isle, şey]   
853  [bir, ver, madencilik, ve, doğal, dil, işle, u...   
854  [doğal, dil, işleme, il, ilgil, deney, ola, ya...   
855  [hafta, öğrencilik, hayat, kaldık, yer, deva, ...   

                                                Text_3  
0    yapay zeka nedir ne işe yarar yapay zeka yz bi...  
1    veri analiz edin chatgptyi kullanarak doğal di...  
2    öncelik yapay zeka ne olduğunu iç ne önemli ol...  
3    baidu research çin ön gele ara motor baidun ar...  
4    microsoft ai microsoft yapay zeka teknoloji od...  
..                                                 ...  
851  doğal dil işle alan yük lisansdoktor yapa danı...  
852                                 dogal dil isle şey  
853     bir ver madencilik ve doğal dil işle uygulamas  
854  doğal dil işleme il ilgil deney ola yazılımcı ...  
855  hafta öğrencilik hayat kaldık yer deva ediyoru...  

[856 rows x 3 columns]

In [23]:
vectorizer = CountVectorizer()
X=vectorizer.fit_transform(df["Text_3"].tolist())
X

<856x4810 sparse matrix of type '<class 'numpy.int64'>'
	with 18143 stored elements in Compressed Sparse Row format>

In [24]:
print(X.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [25]:
X[0]

<1x4810 sparse matrix of type '<class 'numpy.int64'>'
	with 31 stored elements in Compressed Sparse Row format>

In [26]:
df["Text_4"]=X.toarray().tolist()
df.head()

Text   
0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...  \
1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2  Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3  9. Baidu Research: Çin'in önde gelen arama mot...   
4  4. Microsoft AI: Microsoft'un yapay zeka tekno...   

                                              Text_2   
0  [yapay, zeka, nedir, ne, işe, yarar, yapay, ze...  \
1  [veri, analiz, edin, chatgptyi, kullanarak, do...   
2  [öncelik, yapay, zeka, ne, olduğunu, iç, ne, ö...   
3  [baidu, research, çin, ön, gele, ara, motor, b...   
4  [microsoft, ai, microsoft, yapay, zeka, teknol...   

                                              Text_3   
0  yapay zeka nedir ne işe yarar yapay zeka yz bi...  \
1  veri analiz edin chatgptyi kullanarak doğal di...   
2  öncelik yapay zeka ne olduğunu iç ne önemli ol...   
3  baidu research çin ön gele ara motor baidun ar...   
4  microsoft ai microsoft yapay zeka teknoloji od...   

                                              Text_4  
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
2  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...

TfiDf -> Bir kelimenin bir belgedeki frekansını (TF) ve tüm belgelerdeki yaygınlığını (IDF) birleştirerek bir kelimenin önemini ölçer.

In [27]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer=TfidfVectorizer()
X=vectorizer.fit_transform(df["Text_3"].tolist())

In [28]:
print(X.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [29]:
set(X.toarray()[0])

{0.0,
 0.034529070849074917,
 0.03622575493051819,
 0.06380954274919588,
 0.11306928983235955,
 0.12113530293154322,
 0.12593707722050587,
 0.12725540952048855,
 0.1468953954470458,
 0.15077680730861912,
 0.15217931312202868,
 0.15364417262024727,
 0.16413846903940033,
 0.17098099851648932,
 0.17361871890860822,
 0.18698038063938943,
 0.19646063050859733,
 0.20242314449413515,
 0.20982229223937857,
 0.21869940280667285,
 0.21930254210858646,
 0.23266420383936767,
 0.31105993894123957}

In [30]:
df["Text_5"]=X.toarray().tolist()
df

Text   
0    Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...  \
1    🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2    Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3    9. Baidu Research: Çin'in önde gelen arama mot...   
4    4. Microsoft AI: Microsoft'un yapay zeka tekno...   
..                                                 ...   
851  doğal dil işleme alanında yüksek lisans-doktor...   
852                           dogal dil isleme şeyleri   
853  Bir veri madenciliği ve doğal dil işleme uygul...   
854  "Doğal dil işleme" ile ilgili deneyimi olan ya...   
855  Haftaya öğrencilik hayatıma kaldığım yerden de...   

                                                Text_2   
0    [yapay, zeka, nedir, ne, işe, yarar, yapay, ze...  \
1    [veri, analiz, edin, chatgptyi, kullanarak, do...   
2    [öncelik, yapay, zeka, ne, olduğunu, iç, ne, ö...   
3    [baidu, research, çin, ön, gele, ara, motor, b...   
4    [microsoft, ai, microsoft, yapay, zeka, teknol...   
..                                                 ...   
851  [doğal, dil, işle, alan, yük, lisansdoktor, ya...   
852                            [dogal, dil, isle, şey]   
853  [bir, ver, madencilik, ve, doğal, dil, işle, u...   
854  [doğal, dil, işleme, il, ilgil, deney, ola, ya...   
855  [hafta, öğrencilik, hayat, kaldık, yer, deva, ...   

                                                Text_3   
0    yapay zeka nedir ne işe yarar yapay zeka yz bi...  \
1    veri analiz edin chatgptyi kullanarak doğal di...   
2    öncelik yapay zeka ne olduğunu iç ne önemli ol...   
3    baidu research çin ön gele ara motor baidun ar...   
4    microsoft ai microsoft yapay zeka teknoloji od...   
..                                                 ...   
851  doğal dil işle alan yük lisansdoktor yapa danı...   
852                                 dogal dil isle şey   
853     bir ver madencilik ve doğal dil işle uygulamas   
854  doğal dil işleme il ilgil deney ola yazılımcı ...   
855  hafta öğrencilik hayat kaldık yer deva ediyoru...   

                                                Text_4   
0    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  \
1    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
..                                                 ...   
851  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
852  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
853  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
854  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
855  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                                Text_5  
0    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
1    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
3    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
4    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
..                                                 ...  
851  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
852  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
853  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
854  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
855  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  

[856 rows x 5 columns]

Word2vec  -> Kelimelerin anlamsal benzerliklerini ve ilişkilerini temsil etmek amacıyla kelime vektörlerini hesaplar. Bu vektörler, kelimenin çevresindeki diğer kelimelerle olan ilişkisini yansıtır.

In [31]:
!pip install gensim

In [32]:
from gensim.models import Word2Vec

In [33]:
df.head()

Text   
0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...  \
1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2  Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3  9. Baidu Research: Çin'in önde gelen arama mot...   
4  4. Microsoft AI: Microsoft'un yapay zeka tekno...   

                                              Text_2   
0  [yapay, zeka, nedir, ne, işe, yarar, yapay, ze...  \
1  [veri, analiz, edin, chatgptyi, kullanarak, do...   
2  [öncelik, yapay, zeka, ne, olduğunu, iç, ne, ö...   
3  [baidu, research, çin, ön, gele, ara, motor, b...   
4  [microsoft, ai, microsoft, yapay, zeka, teknol...   

                                              Text_3   
0  yapay zeka nedir ne işe yarar yapay zeka yz bi...  \
1  veri analiz edin chatgptyi kullanarak doğal di...   
2  öncelik yapay zeka ne olduğunu iç ne önemli ol...   
3  baidu research çin ön gele ara motor baidun ar...   
4  microsoft ai microsoft yapay zeka teknoloji od...   

                                              Text_4   
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  \
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                              Text_5  
0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
1  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
3  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
4  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...

In [34]:
model=Word2Vec(sentences=df["Text_2"].tolist(),vector_size=100, window=5,min_count=1)
model.save("data/word2vec.model")

In [35]:
print(model)

Word2Vec<vocab=4821, vector_size=100, alpha=0.025>


In [36]:
words=list(model.wv.index_to_key)
words[0:6]

['dil', 'doğal', 'işle', 've', 'bir', 'yapay']

In [37]:
len(words)

4821

In [38]:
df

Text   
0    Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...  \
1    🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2    Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3    9. Baidu Research: Çin'in önde gelen arama mot...   
4    4. Microsoft AI: Microsoft'un yapay zeka tekno...   
..                                                 ...   
851  doğal dil işleme alanında yüksek lisans-doktor...   
852                           dogal dil isleme şeyleri   
853  Bir veri madenciliği ve doğal dil işleme uygul...   
854  "Doğal dil işleme" ile ilgili deneyimi olan ya...   
855  Haftaya öğrencilik hayatıma kaldığım yerden de...   

                                                Text_2   
0    [yapay, zeka, nedir, ne, işe, yarar, yapay, ze...  \
1    [veri, analiz, edin, chatgptyi, kullanarak, do...   
2    [öncelik, yapay, zeka, ne, olduğunu, iç, ne, ö...   
3    [baidu, research, çin, ön, gele, ara, motor, b...   
4    [microsoft, ai, microsoft, yapay, zeka, teknol...   
..                                                 ...   
851  [doğal, dil, işle, alan, yük, lisansdoktor, ya...   
852                            [dogal, dil, isle, şey]   
853  [bir, ver, madencilik, ve, doğal, dil, işle, u...   
854  [doğal, dil, işleme, il, ilgil, deney, ola, ya...   
855  [hafta, öğrencilik, hayat, kaldık, yer, deva, ...   

                                                Text_3   
0    yapay zeka nedir ne işe yarar yapay zeka yz bi...  \
1    veri analiz edin chatgptyi kullanarak doğal di...   
2    öncelik yapay zeka ne olduğunu iç ne önemli ol...   
3    baidu research çin ön gele ara motor baidun ar...   
4    microsoft ai microsoft yapay zeka teknoloji od...   
..                                                 ...   
851  doğal dil işle alan yük lisansdoktor yapa danı...   
852                                 dogal dil isle şey   
853     bir ver madencilik ve doğal dil işle uygulamas   
854  doğal dil işleme il ilgil deney ola yazılımcı ...   
855  hafta öğrencilik hayat kaldık yer deva ediyoru...   

                                                Text_4   
0    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  \
1    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
..                                                 ...   
851  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
852  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
853  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
854  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
855  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                                Text_5  
0    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
1    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
3    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
4    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
..                                                 ...  
851  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
852  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
853  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
854  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
855  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  

[856 rows x 5 columns]

In [39]:
model.wv.key_to_index["yapay"]

5

In [40]:
model.wv[3]

array([-0.31986514,  0.44260943,  0.09162615,  0.0876123 ,  0.22368805,
       -0.62314713,  0.3930128 ,  0.9188154 , -0.23673663, -0.2524263 ,
       -0.02457055, -0.770601  , -0.15307857,  0.26998767,  0.17853795,
       -0.39655006,  0.27744883, -0.34441856, -0.21329658, -1.0301797 ,
        0.31540847,  0.02384909,  0.30890292,  0.03689643, -0.04570508,
        0.20410657, -0.13357162, -0.31367105, -0.37346357, -0.05574933,
        0.5145302 , -0.13375837,  0.14285521, -0.60100365, -0.32196456,
        0.5439847 ,  0.04996752, -0.10594527, -0.2332669 , -0.5396085 ,
       -0.11049215, -0.30469543, -0.12708913,  0.1123922 ,  0.485362  ,
       -0.14354791, -0.3440759 , -0.06175866,  0.1345551 ,  0.20217416,
        0.31386182, -0.37354732, -0.24591042, -0.17577611, -0.24049619,
        0.038046  ,  0.44359052, -0.04345731, -0.3923691 , -0.02246277,
       -0.01949816,  0.1964979 ,  0.17111585, -0.00783597, -0.53377616,
        0.29538396,  0.05710012,  0.43372655, -0.57554585,  0.45

In [41]:
model.wv.get_vector("yapay")

array([-0.2138002 ,  0.28728732,  0.06059211,  0.04695781,  0.13427095,
       -0.40748632,  0.25921246,  0.6020151 , -0.16993019, -0.16973744,
       -0.02833595, -0.5111929 , -0.11347406,  0.16920435,  0.10930583,
       -0.26911277,  0.17030722, -0.23117916, -0.1367534 , -0.6853246 ,
        0.1966332 ,  0.01636372,  0.20578197,  0.02815164, -0.03547719,
        0.12798889, -0.08762147, -0.2194907 , -0.24519405, -0.02799683,
        0.34270388, -0.09536929,  0.09187923, -0.40201414, -0.2126292 ,
        0.3619012 ,  0.03399668, -0.05937316, -0.14254518, -0.3643415 ,
       -0.06324611, -0.2138907 , -0.092985  ,  0.07329968,  0.3132265 ,
       -0.10070912, -0.23007509, -0.02985436,  0.09006027,  0.13359563,
        0.20697013, -0.25661942, -0.14546937, -0.09982955, -0.1637692 ,
        0.028713  ,  0.30199236, -0.04294317, -0.26936042, -0.02017532,
       -0.00282351,  0.12784444,  0.1164452 , -0.01650261, -0.34887955,
        0.19988935,  0.03890634,  0.28071833, -0.3847896 ,  0.29

In [42]:
def word2vec(value):
    model=Word2Vec.load("data/word2vec.model")
    bfr_list=[]
    bfr_len=len(value)
    
    for k in value:
        bfr=model.wv.key_to_index[k]
        bfr=model.wv[bfr]
        bfr_list.append(bfr)

    bfr_list=sum(bfr_list)
    bfr_list=bfr_list/bfr_len
    return bfr_list.tolist()

In [43]:
df.head()

Text   
0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...  \
1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2  Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3  9. Baidu Research: Çin'in önde gelen arama mot...   
4  4. Microsoft AI: Microsoft'un yapay zeka tekno...   

                                              Text_2   
0  [yapay, zeka, nedir, ne, işe, yarar, yapay, ze...  \
1  [veri, analiz, edin, chatgptyi, kullanarak, do...   
2  [öncelik, yapay, zeka, ne, olduğunu, iç, ne, ö...   
3  [baidu, research, çin, ön, gele, ara, motor, b...   
4  [microsoft, ai, microsoft, yapay, zeka, teknol...   

                                              Text_3   
0  yapay zeka nedir ne işe yarar yapay zeka yz bi...  \
1  veri analiz edin chatgptyi kullanarak doğal di...   
2  öncelik yapay zeka ne olduğunu iç ne önemli ol...   
3  baidu research çin ön gele ara motor baidun ar...   
4  microsoft ai microsoft yapay zeka teknoloji od...   

                                              Text_4   
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  \
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                              Text_5  
0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
1  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
3  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
4  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...

In [44]:
df["Text_6"]=df["Text_2"].apply(word2vec)

In [45]:
df.head()

Text   
0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...  \
1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2  Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3  9. Baidu Research: Çin'in önde gelen arama mot...   
4  4. Microsoft AI: Microsoft'un yapay zeka tekno...   

                                              Text_2   
0  [yapay, zeka, nedir, ne, işe, yarar, yapay, ze...  \
1  [veri, analiz, edin, chatgptyi, kullanarak, do...   
2  [öncelik, yapay, zeka, ne, olduğunu, iç, ne, ö...   
3  [baidu, research, çin, ön, gele, ara, motor, b...   
4  [microsoft, ai, microsoft, yapay, zeka, teknol...   

                                              Text_3   
0  yapay zeka nedir ne işe yarar yapay zeka yz bi...  \
1  veri analiz edin chatgptyi kullanarak doğal di...   
2  öncelik yapay zeka ne olduğunu iç ne önemli ol...   
3  baidu research çin ön gele ara motor baidun ar...   
4  microsoft ai microsoft yapay zeka teknoloji od...   

                                              Text_4   
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  \
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                              Text_5   
0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  \
1  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
2  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
3  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
4  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   

                                              Text_6  
0  [-0.10921064019203186, 0.15184874832630157, 0....  
1  [-0.07862260192632675, 0.10715070366859436, 0....  
2  [-0.10248371213674545, 0.1402277648448944, 0.0...  
3  [-0.09586803615093231, 0.13144102692604065, 0....  
4  [-0.1306014508008957, 0.18092893064022064, 0.0...

In [46]:
df["bow"]=on_islem.bag_of_words(df["Text_3"])
df["tfidf"]=on_islem.tfidf(df["Text_3"])
df["word2vec"]=df["Text_2"].apply(on_islem.word2vec)

In [47]:
df.head()

Text   
0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...  \
1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2  Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3  9. Baidu Research: Çin'in önde gelen arama mot...   
4  4. Microsoft AI: Microsoft'un yapay zeka tekno...   

                                              Text_2   
0  [yapay, zeka, nedir, ne, işe, yarar, yapay, ze...  \
1  [veri, analiz, edin, chatgptyi, kullanarak, do...   
2  [öncelik, yapay, zeka, ne, olduğunu, iç, ne, ö...   
3  [baidu, research, çin, ön, gele, ara, motor, b...   
4  [microsoft, ai, microsoft, yapay, zeka, teknol...   

                                              Text_3   
0  yapay zeka nedir ne işe yarar yapay zeka yz bi...  \
1  veri analiz edin chatgptyi kullanarak doğal di...   
2  öncelik yapay zeka ne olduğunu iç ne önemli ol...   
3  baidu research çin ön gele ara motor baidun ar...   
4  microsoft ai microsoft yapay zeka teknoloji od...   

                                              Text_4   
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  \
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                              Text_5   
0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  \
1  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
2  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
3  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
4  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   

                                              Text_6   
0  [-0.10921064019203186, 0.15184874832630157, 0....  \
1  [-0.07862260192632675, 0.10715070366859436, 0....   
2  [-0.10248371213674545, 0.1402277648448944, 0.0...   
3  [-0.09586803615093231, 0.13144102692604065, 0....   
4  [-0.1306014508008957, 0.18092893064022064, 0.0...   

                                                 bow   
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  \
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                               tfidf   
0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  \
1  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
2  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
3  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
4  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   

                                            word2vec  
0  [-0.10921064019203186, 0.15184874832630157, 0....  
1  [-0.07862260192632675, 0.10715070366859436, 0....  
2  [-0.10248371213674545, 0.1402277648448944, 0.0...  
3  [-0.09586803615093231, 0.13144102692604065, 0....  
4  [-0.1306014508008957, 0.18092893064022064, 0.0...